const forbiddenWordsCards = [
    // --- ANIMALS ---
    { word: "Dog", forbidden: ["Pet", "Bark", "Puppy", "Bone", "Loyal"] },
    { word: "Cat", forbidden: ["Meow", "Kitten", "Purr", "Fur", "Pet"] },
    { word: "Lion", forbidden: ["King", "Jungle", "Roar", "Cat", "Mane"] },
    { word: "Tiger", forbidden: ["Stripes", "Orange", "Cat", "Jungle", "Roar"] },
    { word: "Elephant", forbidden: ["Trunk", "Tusk", "Big", "Ivory", "Ears"] },
    { word: "Giraffe", forbidden: ["Neck", "Tall", "Spots", "Africa", "Leaves"] },
    { word: "Monkey", forbidden: ["Banana", "Tree", "Climb", "Tail", "Ape"] },
    { word: "Bear", forbidden: ["Honey", "Cave", "Hibernation", "Grizzly", "Fur"] },
    { word: "Zebra", forbidden: ["Stripes", "Black", "White", "Horse", "Africa"] },
    { word: "Horse", forbidden: ["Ride", "Saddle", "Gallop", "Pony", "Race"] },
    { word: "Cow", forbidden: ["Milk", "Moo", "Farm", "Beef", "Udder"] },
    { word: "Pig", forbidden: ["Mud", "Oink", "Bacon", "Pink", "Farm"] },
    { word: "Chicken", forbidden: ["Egg", "Cluck", "Farm", "Bird", "Wing"] },
    { word: "Snake", forbidden: ["Slither", "Hiss", "Poison", "Reptile", "Long"] },
    { word: "Spider", forbidden: ["Web", "Legs", "Insect", "Scary", "Bite"] },
    { word: "Shark", forbidden: ["Teeth", "Ocean", "Fin", "Jaws", "Attack"] },
    { word: "Whale", forbidden: ["Blue", "Ocean", "Big", "Blowhole", "Mammal"] },
    { word: "Dolphin", forbidden: ["Swim", "Ocean", "Smart", "Flipper", "Mammal"] },
    { word: "Penguin", forbidden: ["Ice", "Tuxedo", "Bird", "March", "Antarctica"] },
    { word: "Kangaroo", forbidden: ["Pouch", "Hop", "Australia", "Jump", "Joey"] },
    { word: "Panda", forbidden: ["Bamboo", "Bear", "China", "Black", "White"] },
    { word: "Koala", forbidden: ["Eucalyptus", "Bear", "Australia", "Tree", "Cute"] },
    { word: "Frog", forbidden: ["Green", "Jump", "Pond", "Ribbit", "Tadpole"] },
    { word: "Turtle", forbidden: ["Shell", "Slow", "Green", "Ninja", "Reptile"] },
    { word: "Rabbit", forbidden: ["Carrot", "Hop", "Ears", "Bunny", "Easter"] },
    { word: "Mouse", forbidden: ["Cheese", "Squeak", "Trap", "Cat", "Tiny"] },
    { word: "Bat", forbidden: ["Vampire", "Cave", "Fly", "Night", "Sonar"] },
    { word: "Owl", forbidden: ["Hoot", "Night", "Wise", "Bird", "Head"] },
    { word: "Eagle", forbidden: ["Bald", "America", "Bird", "Fly", "Symbol"] },
    { word: "Duck", forbidden: ["Quack", "Pond", "Bird", "Bill", "Feather"] },
    { word: "Goose", forbidden: ["Honk", "Bird", "White", "Chase", "Egg"] },
    { word: "Fox", forbidden: ["Orange", "Sly", "Tail", "Wild", "Dog"] },
    { word: "Wolf", forbidden: ["Howl", "Pack", "Moon", "Wild", "Dog"] },
    { word: "Deer", forbidden: ["Antlers", "Forest", "Bambi", "Hunt", "Doe"] },
    { word: "Bee", forbidden: ["Honey", "Sting", "Yellow", "Hive", "Buzz"] },
    { word: "Butterfly", forbidden: ["Caterpillar", "Wings", "Colorful", "Fly", "Insect"] },
    { word: "Ant", forbidden: ["Small", "Hill", "Picnic", "Insect", "Work"] },
    { word: "Octopus", forbidden: ["Eight", "Tentacles", "Ink", "Ocean", "Sea"] },
    { word: "Jellyfish", forbidden: ["Sting", "Ocean", "Transparent", "Float", "Sea"] },
    { word: "Crab", forbidden: ["Claws", "Beach", "Sideways", "Shell", "Red"] },
    { word: "Lobster", forbidden: ["Red", "Expensive", "Claws", "Seafood", "Ocean"] },
    { word: "Fish", forbidden: ["Swim", "Water", "Gills", "Scales", "Sea"] },
    { word: "Seal", forbidden: ["Bark", "Ocean", "Flipper", "Ice", "Arf"] },
    { word: "Gorilla", forbidden: ["Ape", "King Kong", "Jungle", "Silverback", "Big"] },
    { word: "Rhino", forbidden: ["Horn", "Gray", "Africa", "Charge", "Big"] },
    { word: "Hippo", forbidden: ["Water", "Big", "Dangerous", "Mouth", "Hungry"] },
    { word: "Parrot", forbidden: ["Talk", "Bird", "Pirate", "Colorful", "Cracker"] },
    { word: "Flamingo", forbidden: ["Pink", "Stand", "Bird", "Leg", "Lawn"] },
    { word: "Peacock", forbidden: ["Feathers", "Show", "Colorful", "Bird", "Fan"] },
    { word: "Camel", forbidden: ["Hump", "Desert", "Sand", "Water", "Spit"] },
    { word: "Lizard", forbidden: ["Reptile", "Green", "Scales", "Tail", "Cold"] },
    { word: "Crocodile", forbidden: ["Alligator", "Teeth", "Swamp", "Green", "Snap"] },
    { word: "Dinosaur", forbidden: ["Extinct", "Fossil", "Jurassic", "T-Rex", "Lizard"] },
    { word: "Dragon", forbidden: ["Fire", "Myth", "Fly", "Scales", "Breath"] },
    { word: "Unicorn", forbidden: ["Horn", "Horse", "Magic", "Fantasy", "Rainbow"] },
    { word: "Squirrel", forbidden: ["Nut", "Tree", "Tail", "Acorn", "Rodent"] },
    { word: "Raccoon", forbidden: ["Trash", "Mask", "Bandit", "Night", "Garbage"] },
    { word: "Beaver", forbidden: ["Dam", "Wood", "Teeth", "Tail", "River"] },
    { word: "Otter", forbidden: ["Water", "Cute", "Hand", "River", "Sea"] },
    { word: "Sloth", forbidden: ["Slow", "Tree", "Climb", "Lazy", "Animal"] },
    { word: "Cheetah", forbidden: ["Fast", "Run", "Spots", "Cat", "Africa"] },
    { word: "Leopard", forbidden: ["Spots", "Cat", "Tree", "Jungle", "Africa"] },
    { word: "Panther", forbidden: ["Black", "Cat", "Jungle", "Bagheera", "Wild"] },
    { word: "Mosquito", forbidden: ["Bite", "Itch", "Blood", "Fly", "Insect"] },
    { word: "Fly", forbidden: ["Buzz", "Insect", "Annoying", "Swatter", "Garbage"] },
    { word: "Worm", forbidden: ["Dirt", "Ground", "Hook", "Fish", "Squirm"] },
    { word: "Snail", forbidden: ["Shell", "Slow", "Slime", "Garden", "Escargot"] },

    // --- FOOD --
    { word: "Pizza", forbidden: ["Cheese", "Pepperoni", "Italy", "Slice", "Deep Dish"] },
    { word: "Burger", forbidden: ["Bun", "Meat", "Cheese", "Fries", "McDonalds"] },
    { word: "Hot Dog", forbidden: ["Bun", "Sausage", "Mustard", "Baseball", "Ketchup"] },
    { word: "Fries", forbidden: ["Potato", "Salty", "Ketchup", "Fast Food", "Yellow"] },
    { word: "Taco", forbidden: ["Shell", "Mexican", "Meat", "Crunchy", "Tuesday"] },
    { word: "Burrito", forbidden: ["Wrap", "Bean", "Rice", "Mexican", "Chipotle"] },
    { word: "Sushi", forbidden: ["Raw", "Fish", "Rice", "Roll", "Japan"] },
    { word: "Spaghetti", forbidden: ["Pasta", "Noodle", "Meatball", "Italian", "Sauce"] },
    { word: "Lasagna", forbidden: ["Layer", "Cheese", "Pasta", "Garfield", "Italian"] },
    { word: "Salad", forbidden: ["Green", "Lettuce", "Healthy", "Vegetable", "Dressing"] },
    { word: "Soup", forbidden: ["Bowl", "Spoon", "Hot", "Liquid", "Chicken"] },
    { word: "Sandwich", forbidden: ["Bread", "Lunch", "Meat", "Sub", "Cheese"] },
    { word: "Steak", forbidden: ["Meat", "Beef", "Cow", "Grill", "Rare"] },
    { word: "Chicken", forbidden: ["Bird", "Fried", "Meat", "Wing", "Dinner"] },
    { word: "Bacon", forbidden: ["Pig", "Breakfast", "Crispy", "Grease", "Frying"] },
    { word: "Egg", forbidden: ["Chicken", "Shell", "Breakfast", "Yolk", "White"] },
    { word: "Pancake", forbidden: ["Syrup", "Breakfast", "Stack", "Flat", "Flapjack"] },
    { word: "Waffle", forbidden: ["Syrup", "Grid", "Breakfast", "Square", "Iron"] },
    { word: "Cereal", forbidden: ["Milk", "Bowl", "Breakfast", "Spoon", "Box"] },
    { word: "Toast", forbidden: ["Bread", "Butter", "Breakfast", "Jam", "Toaster"] },
    { word: "Cheese", forbidden: ["Milk", "Yellow", "Mouse", "Swiss", "Cheddar"] },
    { word: "Butter", forbidden: ["Yellow", "Bread", "Melt", "Milk", "Stick"] },
    { word: "Yogurt", forbidden: ["Dairy", "Spoon", "Culture", "Greek", "Healthy"] },
    { word: "Ice Cream", forbidden: ["Cold", "Cone", "Scoop", "Vanilla", "Dessert"] },
    { word: "Chocolate", forbidden: ["Sweet", "Candy", "Bar", "Cocoa", "Dark"] },
    { word: "Cake", forbidden: ["Birthday", "Candle", "Sweet", "Dessert", "Bake"] },
    { word: "Cookie", forbidden: ["Milk", "Chip", "Bake", "Sweet", "Dough"] },
    { word: "Donut", forbidden: ["Hole", "Glaze", "Sweet", "Coffee", "Cop"] },
    { word: "Pie", forbidden: ["Crust", "Apple", "Slice", "Dessert", "Thanksgiving"] },
    { word: "Candy", forbidden: ["Sweet", "Sugar", "Halloween", "Wrapper", "Treat"] },
    { word: "Popcorn", forbidden: ["Movie", "Kernel", "Butter", "Salt", "Microwave"] },
    { word: "Chips", forbidden: ["Potato", "Bag", "Salty", "Crunchy", "Snack"] },
    { word: "Apple", forbidden: ["Red", "Fruit", "Pie", "Tree", "Teacher"] },
    { word: "Banana", forbidden: ["Yellow", "Peel", "Monkey", "Fruit", "Split"] },
    { word: "Orange", forbidden: ["Juice", "Fruit", "Vitamin C", "Peel", "Citrus"] },
    { word: "Grape", forbidden: ["Purple", "Green", "Vine", "Wine", "Bunch"] },
    { word: "Strawberry", forbidden: ["Red", "Berry", "Shortcake", "Fruit", "Seed"] },
    { word: "Watermelon", forbidden: ["Summer", "Seed", "Green", "Red", "Fruit"] },
    { word: "Lemon", forbidden: ["Sour", "Yellow", "Citrus", "Aid", "Fruit"] },
    { word: "Pineapple", forbidden: ["Yellow", "Tropical", "SpongeBob", "Fruit", "Pizza"] },
    { word: "Peach", forbidden: ["Fuzzy", "Fruit", "Pit", "Cobbler", "Georgia"] },
    { word: "Cherry", forbidden: ["Red", "Pit", "Top", "Fruit", "Sundae"] },
    { word: "Potato", forbidden: ["Spud", "Fries", "Mashed", "Skin", "Vegetable"] },
    { word: "Tomato", forbidden: ["Red", "Ketchup", "Fruit", "Sauce", "Salad"] },
    { word: "Carrot", forbidden: ["Rabbit", "Orange", "Vegetable", "Root", "Vision"] },
    { word: "Onion", forbidden: ["Cry", "Layers", "Smell", "Vegetable", "White"] },
    { word: "Garlic", forbidden: ["Smell", "Vampire", "Italian", "Bread", "Clove"] },
    { word: "Corn", forbidden: ["Cob", "Yellow", "Kernel", "Pop", "Vegetable"] },
    { word: "Broccoli", forbidden: ["Green", "Tree", "Vegetable", "Healthy", "Stalk"] },
    { word: "Pepper", forbidden: ["Salt", "Spicy", "Vegetable", "Red", "Green"] },
    { word: "Salt", forbidden: ["Pepper", "White", "Sea", "Shake", "Taste"] },
    { word: "Sugar", forbidden: ["Sweet", "White", "Cane", "Cookie", "Spice"] },
    { word: "Coffee", forbidden: ["Caffeine", "Drink", "In Morning", "Mug", "Starbucks"] },
    { word: "Tea", forbidden: ["Bag", "Drink", "Cup", "Hot", "Iced"] },
    { word: "Soda", forbidden: ["Pop", "Drink", "Carbonated", "Coke", "Pepsi"] },
    { word: "Water", forbidden: ["Drink", "Wet", "Liquid", "H2O", "Bottle"] },
    { word: "Juice", forbidden: ["Orange", "Drink", "Fruit", "Apple", "Liquid"] },
    { word: "Milkshake", forbidden: ["Ice Cream", "Drink", "Straw", "Dairy", "Thick"] },
    { word: "Lemonade", forbidden: ["Lemon", "Drink", "Stand", "Yellow", "Summer"] },
    { word: "Beer", forbidden: ["Alcohol", "Drink", "Bar", "Brewery", "Pint"] },
    { word: "Wine", forbidden: ["Grape", "Alcohol", "Red", "White", "Glass"] },
    { word: "Bread", forbidden: ["Loaf", "Slice", "Toast", "Sandwich", "Wheat"] },

    // --- HOUSEHOLD ---
    { word: "Chair", forbidden: ["Sit", "Seat", "Furniture", "Table", "Legs"] },
    { word: "Table", forbidden: ["Furniture", "Eat", "Legs", "Wood", "Dinner"] },
    { word: "Sofa", forbidden: ["Couch", "Sit", "Living Room", "Television", "Furniture"] },
    { word: "Bed", forbidden: ["Sleep", "Mattress", "Pillow", "Sheets", "Bedroom"] },
    { word: "Pillow", forbidden: ["Sleep", "Head", "Soft", "Bed", "Feather"] },
    { word: "Blanket", forbidden: ["Warm", "Cover", "Sleep", "Bed", "Comforter"] },
    { word: "Lamp", forbidden: ["Light", "Bulb", "Desk", "Shade", "Turn On"] },
    { word: "Carpet", forbidden: ["Rug", "Floor", "Soft", "Vacuum", "Room"] },
    { word: "Mirror", forbidden: ["Reflection", "Look", "Glass", "Wall", "Face"] },
    { word: "Clock", forbidden: ["Time", "Watch", "Wall", "Hour", "Tick"] },
    { word: "Door", forbidden: ["Open", "Close", "Knob", "Enter", "Lock"] },
    { word: "Window", forbidden: ["Glass", "See", "Open", "View", "Pane"] },
    { word: "Kitchen", forbidden: ["Cook", "Room", "Food", "Stove", "Sink"] },
    { word: "Bathroom", forbidden: ["Toilet", "Shower", "Room", "Wash", "Tub"] },
    { word: "Shower", forbidden: ["Water", "Clean", "Wash", "Bath", "Soap"] },
    { word: "Toilet", forbidden: ["Flush", "Paper", "Bathroom", "Seat", "Potty"] },
    { word: "Toothbrush", forbidden: ["Teeth", "Paste", "Clean", "Brush", "Morning"] },
    { word: "Soap", forbidden: ["Wash", "Clean", "Bubbles", "Bar", "Hands"] },
    { word: "Towel", forbidden: ["Dry", "Bath", "Cloth", "Wet", "Shower"] },
    { word: "Shampoo", forbidden: ["Hair", "Wash", "Shower", "Soap", "Clean"] },
    { word: "Comb", forbidden: ["Hair", "Brush", "Teeth", "Style", "Plastic"] },
    { word: "Refrigerator", forbidden: ["Cold", "Food", "Kitchen", "Ice", "Freezer"] },
    { word: "Oven", forbidden: ["Bake", "Hot", "Kitchen", "Cook", "Stove"] },
    { word: "Microwave", forbidden: ["Heat", "Fast", "Kitchen", "Popcorn", "Cook"] },
    { word: "Stove", forbidden: ["Cook", "Hot", "Burner", "Kitchen", "Gas"] },
    { word: "Sink", forbidden: ["Water", "Wash", "Kitchen", "Drain", "Faucet"] },
    { word: "Spoon", forbidden: ["Soup", "Eat", "Silverware", "Bowl", "Scoop"] },
    { word: "Fork", forbidden: ["Eat", "Prongs", "Silverware", "Knife", "Food"] },
    { word: "Knife", forbidden: ["Cut", "Sharp", "Silverware", "Fork", "Blade"] },
    { word: "Plate", forbidden: ["Dish", "Eat", "Round", "Dinner", "Food"] },
    { word: "Cup", forbidden: ["Drink", "Glass", "Mug", "Liquid", "Hold"] },
    { word: "Glass", forbidden: ["Drink", "Break", "Window", "Clear", "Cup"] },
    { word: "Broom", forbidden: ["Sweep", "Floor", "Dust", "Witch", "Clean"] },
    { word: "Mop", forbidden: ["Wet", "Floor", "Clean", "Bucket", "Wash"] },
    { word: "Vacuum", forbidden: ["Clean", "Carpet", "Suck", "Noise", "Dirt"] },
    { word: "Trash Can", forbidden: ["Garbage", "Rubbish", "Bin", "Waste", "Bag"] },
    { word: "Washer", forbidden: ["Clothes", "Clean", "Laundry", "Machine", "Soap"] },
    { word: "Dryer", forbidden: ["Clothes", "Hot", "Machine", "Laundry", "Wet"] },
    { word: "Iron", forbidden: ["Clothes", "Hot", "Flat", "Wrinkle", "Board"] },
    { word: "Computer", forbidden: ["Laptop", "Screen", "Keyboard", "Internet", "Mouse"] },
    { word: "Television", forbidden: ["Watch", "Screen", "Show", "Remote", "Channel"] },
    { word: "Remote", forbidden: ["TV", "Control", "Buttons", "Change", "Channel"] },
    { word: "Phone", forbidden: ["Call", "Cell", "Talk", "Text", "Mobile"] },
    { word: "Camera", forbidden: ["Picture", "Photo", "Lens", "Shoot", "Smile"] },
    { word: "Picture", forbidden: ["Frame", "Photo", "Wall", "Hang", "Image"] },
    { word: "Key", forbidden: ["Lock", "Door", "Open", "Metal", "Ring"] },
    { word: "Wallet", forbidden: ["Money", "Cash", "Pocket", "Cards", "Leather"] },
    { word: "Purse", forbidden: ["Bag", "Woman", "Money", "Carry", "Shoulder"] },
    { word: "Umbrella", forbidden: ["Rain", "Wet", "Dry", "Open", "Canopy"] },
    { word: "Glasses", forbidden: ["Eyes", "See", "Vision", "Wear", "Frame"] },

    // --- CLOTHING ---
    { word: "Shirt", forbidden: ["Wear", "Top", "Sleeves", "Buttons", "Clothes"] },
    { word: "Pants", forbidden: ["Legs", "Jeans", "Trousers", "Wear", "Pocket"] },
    { word: "Shorts", forbidden: ["Legs", "Summer", "Wear", "Short", "Pants"] },
    { word: "Dress", forbidden: ["Woman", "Wear", "Skirt", "Fancy", "Gown"] },
    { word: "Skirt", forbidden: ["Woman", "Wear", "Legs", "Dress", "Girl"] },
    { word: "Shoe", forbidden: ["Foot", "Walk", "Sock", "Lace", "Sneaker"] },
    { word: "Sock", forbidden: ["Foot", "Shoe", "Warm", "Toe", "Pair"] },
    { word: "Hat", forbidden: ["Head", "Cap", "Wear", "Winter", "Baseball"] },
    { word: "Coat", forbidden: ["Jacket", "Winter", "Cold", "Wear", "Warm"] },
    { word: "Jacket", forbidden: ["Coat", "Zipper", "Wear", "Cold", "Sleeve"] },
    { word: "Glove", forbidden: ["Hand", "Finger", "Winter", "Warm", "Mittens"] },
    { word: "Scarf", forbidden: ["Neck", "Winter", "Warm", "Wool", "Wrap"] },
    { word: "Boots", forbidden: ["Shoes", "Winter", "Feet", "Rain", "Cowboy"] },
    { word: "Sandal", forbidden: ["Shoe", "Summer", "Toe", "Beach", "Flip Flop"] },
    { word: "Belt", forbidden: ["Waist", "Pants", "Buckle", "Hold", "Leather"] },
    { word: "Tie", forbidden: ["Suit", "Neck", "Formal", "Man", "Knot"] },
    { word: "Ring", forbidden: ["Finger", "Jewelry", "Gold", "Wedding", "Diamond"] },
    { word: "Necklace", forbidden: ["Neck", "Jewelry", "Gold", "Chain", "Pendant"] },
    { word: "Earring", forbidden: ["Ear", "Jewelry", "Piercing", "Gold", "Pair"] },
    { word: "Watch", forbidden: ["Time", "Wrist", "Clock", "Wear", "Tell"] },
    { word: "Pajamas", forbidden: ["Sleep", "Bed", "Wear", "Night", "Clothes"] },
    { word: "Suit", forbidden: ["Man", "Formal", "Tie", "Jacket", "Business"] },
    { word: "Uniform", forbidden: ["School", "Work", "Wear", "Same", "Job"] },
    { word: "Zipper", forbidden: ["Close", "Jacket", "Pants", "Metal", "Up"] },
    { word: "Button", forbidden: ["Shirt", "Push", "Round", "Hole", "Fasten"] },
    { word: "Shoelace", forbidden: ["Tie", "Shoe", "Knot", "String", "Foot"] },

    // --- NATURE & PLACES ---
    { word: "Tree", forbidden: ["Leaf", "Green", "Wood", "Branch", "Forest"] },
    { word: "Flower", forbidden: ["Petal", "Smell", "Garden", "Bloom", "Rose"] },
    { word: "Grass", forbidden: ["Green", "Lawn", "Mow", "Ground", "Grow"] },
    { word: "Sun", forbidden: ["Hot", "Yellow", "Sky", "Day", "Star"] },
    { word: "Moon", forbidden: ["Night", "Sky", "Space", "Crescent", "Orbit"] },
    { word: "Star", forbidden: ["Sky", "Night", "Twinkle", "Space", "Shine"] },
    { word: "Cloud", forbidden: ["White", "Sky", "Rain", "Fluffy", "Storm"] },
    { word: "Rain", forbidden: ["Water", "Wet", "Sky", "Storm", "Umbrella"] },
    { word: "Snow", forbidden: ["White", "Cold", "Winter", "Ice", "Flake"] },
    { word: "Wind", forbidden: ["Blow", "Air", "Breeze", "Storm", "Feel"] },
    { word: "Storm", forbidden: ["Rain", "Thunder", "Lightning", "Wind", "Scary"] },
    { word: "Rainbow", forbidden: ["Color", "Sky", "Rain", "Arc", "Pot of Gold"] },
    { word: "Ocean", forbidden: ["Sea", "Water", "Blue", "Beach", "Fish"] },
    { word: "River", forbidden: ["Water", "Flow", "Stream", "Boat", "Bank"] },
    { word: "Lake", forbidden: ["Water", "Boat", "Swim", "Pond", "Fish"] },
    { word: "Mountain", forbidden: ["High", "Climb", "Peak", "Hike", "Snow"] },
    { word: "Desert", forbidden: ["Sand", "Hot", "Dry", "Cactus", "Camel"] },
    { word: "Forest", forbidden: ["Trees", "Woods", "Animals", "Green", "Camping"] },
    { word: "Jungle", forbidden: ["Trees", "Animals", "Tarzan", "Rain", "Wild"] },
    { word: "Beach", forbidden: ["Sand", "Ocean", "Sun", "Vacation", "Swim"] },
    { word: "City", forbidden: ["Building", "People", "Busy", "Town", "Urban"] },
    { word: "Farm", forbidden: ["Animals", "Barn", "Farmer", "Grow", "Tractor"] },
    { word: "Park", forbidden: ["Play", "Slide", "Swing", "Grass", "Bench"] },
    { word: "School", forbidden: ["Learn", "Teacher", "Student", "Class", "Study"] },
    { word: "Library", forbidden: ["Book", "Read", "Quiet", "Study", "Card"] },
    { word: "Hospital", forbidden: ["Sick", "Doctor", "Nurse", "Medicine", "Ambulance"] },
    { word: "Zoo", forbidden: ["Animals", "Cage", "See", "Visit", "Wild"] },
    { word: "Museum", forbidden: ["Art", "Old", "Exhibit", "Look", "History"] },
    { word: "Cinema", forbidden: ["Movie", "Popcorn", "Screen", "Watch", "Film"] },
    { word: "Restaurant", forbidden: ["Eat", "Food", "Menu", "Waiter", "Dinner"] },
    { word: "Hotel", forbidden: ["Sleep", "Stay", "Room", "Vacation", "Bed"] },
    { word: "Airport", forbidden: ["Plane", "Fly", "Travel", "Suitcase", "Gate"] },
    { word: "Train Station", forbidden: ["Train", "Track", "Ride", "Wait", "Platform"] },
    { word: "Bank", forbidden: ["Money", "Cash", "Save", "Teller", "Account"] },
    { word: "Post Office", forbidden: ["Mail", "Letter", "Stamp", "Box", "Send"] },
    { word: "Fire Station", forbidden: ["Truck", "Firefighter", "Siren", "Pole", "Hose"] },
    { word: "Police Station", forbidden: ["Cop", "Jail", "Badge", "Officer", "Law"] },
    { word: "Church", forbidden: ["Pray", "Religion", "Sunday", "Building", "God"] },
    { word: "Stadium", forbidden: ["Sports", "Game", "Seat", "Crowd", "Field"] },
    { word: "Gym", forbidden: ["Exercise", "Workout", "Sweat", "Muscle", "Run"] },

    // --- JOBS ---
    { word: "Doctor", forbidden: ["Hospital", "Medicine", "Sick", "Heal", "Nurse"] },
    { word: "Teacher", forbidden: ["School", "Student", "Learn", "Class", "Grade"] },
    { word: "Police Officer", forbidden: ["Cop", "Badge", "Stop", "Arrest", "Law"] },
    { word: "Firefighter", forbidden: ["Fire", "Truck", "Hose", "Water", "Helmet"] },
    { word: "Nurse", forbidden: ["Doctor", "Hospital", "Sick", "Help", "Medicine"] },
    { word: "Chef", forbidden: ["Cook", "Food", "Kitchen", "Restaurant", "Hat"] },
    { word: "Farmer", forbidden: ["Farm", "Grow", "Animals", "Tractor", "Crops"] },
    { word: "Pilot", forbidden: ["Plane", "Fly", "Sky", "Airport", "Captain"] },
    { word: "Astronaut", forbidden: ["Space", "Moon", "Rocket", "NASA", "Suit"] },
    { word: "Artist", forbidden: ["Paint", "Draw", "Picture", "Brush", "Create"] },
    { word: "Singer", forbidden: ["Song", "Music", "Voice", "Microphone", "Concert"] },
    { word: "Actor", forbidden: ["Movie", "Play", "Star", "Film", "Perform"] },
    { word: "Dentist", forbidden: ["Teeth", "Mouth", "Drill", "Clean", "Smile"] },
    { word: "Vet", forbidden: ["Animal", "Doctor", "Pet", "Sick", "Dog"] },
    { word: "Scientist", forbidden: ["Lab", "Experiment", "Chemical", "Research", "Coat"] },
    { word: "Soldier", forbidden: ["Army", "War", "Uniform", "Gun", "Fight"] },
    { word: "Judge", forbidden: ["Court", "Law", "Gavel", "Guilty", "Robe"] },
    { word: "Mechanic", forbidden: ["Car", "Fix", "Engine", "Tool", "Garage"] },
    { word: "Waiter", forbidden: ["Food", "Restaurant", "Serve", "Table", "Order"] },
    { word: "Librarian", forbidden: ["Book", "Library", "Read", "Quiet", "Shelf"] },
    { word: "Mail Carrier", forbidden: ["Letter", "Post", "Deliver", "Bag", "Mailbox"] },
    { word: "Clown", forbidden: ["Circus", "Funny", "Nose", "Makeup", "Balloon"] },
    { word: "Magician", forbidden: ["Magic", "Trick", "Rabbit", "Hat", "Wand"] },
    { word: "Pirate", forbidden: ["Ship", "Treasure", "Sea", "Eye Patch", "Hook"] },
    { word: "King", forbidden: ["Queen", "Crown", "Rule", "Throne", "Royal"] },

    // --- SPORTS & HOBBIES ---
    { word: "Soccer", forbidden: ["Ball", "Kick", "Goal", "Team", "Field"] },
    { word: "Basketball", forbidden: ["Ball", "Hoop", "Court", "Dribble", "Shot"] },
    { word: "Baseball", forbidden: ["Bat", "Ball", "Hit", "Home Run", "Mitt"] },
    { word: "Football", forbidden: ["Ball", "Touchdown", "Helmet", "Tackle", "Field"] },
    { word: "Tennis", forbidden: ["Racket", "Ball", "Net", "Court", "Serve"] },
    { word: "Golf", forbidden: ["Club", "Ball", "Hole", "Course", "Drive"] },
    { word: "Swimming", forbidden: ["Water", "Pool", "Race", "Stroke", "Wet"] },
    { word: "Running", forbidden: ["Fast", "Race", "Shoes", "Track", "Jog"] },
    { word: "Bowling", forbidden: ["Ball", "Pins", "Lane", "Strike", "Shoes"] },
    { word: "Volleyball", forbidden: ["Net", "Ball", "Spike", "Sand", "Team"] },
    { word: "Hockey", forbidden: ["Ice", "Skate", "Puck", "Stick", "Goal"] },
    { word: "Boxing", forbidden: ["Fight", "Gloves", "Ring", "Punch", "Round"] },
    { word: "Skiing", forbidden: ["Snow", "Mountain", "Poles", "Winter", "Slope"] },
    { word: "Fishing", forbidden: ["Rod", "Hook", "Fish", "Water", "Bait"] },
    { word: "Camping", forbidden: ["Tent", "Fire", "Outside", "Sleep", "Woods"] },
    { word: "Reading", forbidden: ["Book", "Story", "Words", "Library", "Pages"] },
    { word: "Writing", forbidden: ["Pen", "Paper", "Story", "Words", "Pencil"] },
    { word: "Drawing", forbidden: ["Pencil", "Paper", "Picture", "Art", "Sketch"] },
    { word: "Dancing", forbidden: ["Music", "Move", "Step", "Song", "Ballet"] },
    { word: "Singing", forbidden: ["Voice", "Song", "Music", "Mouth", "Tune"] },
    { word: "Chess", forbidden: ["Board", "King", "Queen", "Checkmate", "Game"] },
    { word: "Video Game", forbidden: ["Play", "Controller", "Screen", "Console", "Computer"] },
    { word: "Guitar", forbidden: ["String", "Music", "Play", "Instrument", "Rock"] },
    { word: "Piano", forbidden: ["Keys", "Music", "Play", "Black", "White"] },
    { word: "Drums", forbidden: ["Beat", "Stick", "Music", "Loud", "Instrument"] },

    // --- TRANSPORTAL ---
    { word: "Car", forbidden: ["Drive", "Wheel", "Ride", "Road", "Engine"] },
    { word: "Bus", forbidden: ["School", "Ride", "Drive", "Yellow", "Stop"] },
    { word: "Truck", forbidden: ["Big", "Drive", "Load", "Pickup", "Haul"] },
    { word: "Train", forbidden: ["Track", "Choo Choo", "Ride", "Engine", "Rail"] },
    { word: "Airplane", forbidden: ["Fly", "Sky", "Wings", "Airport", "Pilot"] },
    { word: "Boat", forbidden: ["Water", "Float", "Ship", "Sail", "Sea"] },
    { word: "Ship", forbidden: ["Boat", "Big", "Ocean", "Water", "Captain"] },
    { word: "Bicycle", forbidden: ["Ride", "Wheel", "Pedal", "Helmet", "Two"] },
    { word: "Motorcycle", forbidden: ["Bike", "Engine", "Helmet", "Fast", "Ride"] },
    { word: "Helicopter", forbidden: ["Fly", "Blade", "Chopper", "Sky", "Pilot"] },
    { word: "Rocket", forbidden: ["Space", "Fly", "Moon", "NASA", "Blast Off"] },
    { word: "Subway", forbidden: ["Train", "Underground", "City", "Track", "Metro"] },
    { word: "Taxi", forbidden: ["Car", "Yellow", "Pay", "Driver", "Ride"] },
    { word: "Ambulance", forbidden: ["Siren", "Hospital", "Emergency", "Red", "Sick"] },
    { word: "Fire Truck", forbidden: ["Red", "Siren", "Hose", "Ladder", "Fire"] },
    { word: "School Bus", forbidden: ["Yellow", "Kids", "School", "Ride", "Driver"] },
    { word: "Tractor", forbidden: ["Farm", "Green", "Drive", "Field", "Slow"] },
    { word: "Skateboard", forbidden: ["Wheels", "Ride", "Trick", "Board", "Helmet"] },
    { word: "Scooter", forbidden: ["Ride", "Wheels", "Handle", "Push", "Fast"] },
    { word: "Van", forbidden: ["Car", "Big", "Drive", "Family", "Box"] },

    // --- CONCEPTS & ADJECTIVES ---
    { word: "Happy", forbidden: ["Smile", "Glad", "Sad", "Face", "Feeling"] },
    { word: "Sad", forbidden: ["Cry", "Happy", "Tears", "Blue", "Unhappy"] },
    { word: "Angry", forbidden: ["Mad", "Red", "Yell", "Face", "Upset"] },
    { word: "Scary", forbidden: ["Afraid", "Ghost", "Monster", "Dark", "Fear"] },
    { word: "Funny", forbidden: ["Laugh", "Joke", "Clown", "Ha Ha", "Silly"] },
    { word: "Hot", forbidden: ["Cold", "Fire", "Sun", "Burn", "Summer"] },
    { word: "Cold", forbidden: ["Hot", "Ice", "Snow", "Winter", "Freezing"] },
    { word: "Big", forbidden: ["Small", "Giant", "Large", "Huge", "Size"] },
    { word: "Small", forbidden: ["Big", "Tiny", "Little", "Mini", "Micro"] },
    { word: "Fast", forbidden: ["Slow", "Run", "Speed", "Quick", "Race"] },
    { word: "Slow", forbidden: ["Fast", "Turtle", "Snail", "Speed", "Late"] },
    { word: "Old", forbidden: ["New", "Age", "Grandpa", "Ancient", "Used"] },
    { word: "New", forbidden: ["Old", "Fresh", "Shiny", "Brand", "Recent"] },
    { word: "Rich", forbidden: ["Money", "Poor", "Millionaire", "Wealthy", "Cash"] },
    { word: "Poor", forbidden: ["Money", "Rich", "Broke", "No", "Penny"] },
    { word: "Good", forbidden: ["Bad", "Nice", "Great", "Behavior", "Well"] },
    { word: "Bad", forbidden: ["Good", "Naughty", "Evil", "Wrong", "Trouble"] },
    { word: "Love", forbidden: ["Heart", "Hate", "Like", "Kiss", "Feeling"] },
    { word: "Hate", forbidden: ["Love", "Dislike", "Mad", "Enemy", "Feeling"] },
    { word: "Beautiful", forbidden: ["Pretty", "Ugly", "Look", "Gorgeous", "Nice"] },
    { word: "Ugly", forbidden: ["Beautiful", "Pretty", "Look", "Face", "Bad"] },
    { word: "Smart", forbidden: ["Brain", "Intelligent", "Dumb", "School", "Think"] },
    { word: "Strong", forbidden: ["Weak", "Muscle", "Power", "Lift", "Heavy"] },
    { word: "Weak", forbidden: ["Strong", "Muscle", "Power", "No", "Frail"] },
    { word: "Loud", forbidden: ["Quiet", "Noise", "Yell", "Sound", "Hear"] },
    { word: "Quiet", forbidden: ["Loud", "Shhh", "Silence", "Noise", "Library"] },
    { word: "Dark", forbidden: ["Light", "Night", "Black", "See", "Room"] },
    { word: "Light", forbidden: ["Dark", "Sun", "Lamp", "Bright", "See"] },
    { word: "Heavy", forbidden: ["Weight", "Light", "Lift", "Strong", "Pound"] },
    { word: "Wet", forbidden: ["Water", "Dry", "Rain", "Soak", "Liquid"] },
    { word: "Dry", forbidden: ["Wet", "Water", "Towel", "Thirsty", "Desert"] },
    { word: "Clean", forbidden: ["Dirty", "Wash", "Soap", "Mess", "Sparkle"] },
    { word: "Dirty", forbidden: ["Clean", "Mess", "Wash", "Mud", "Filth"] },
    { word: "Hard", forbidden: ["Soft", "Rock", "Difficult", "Solid", "Tough"] },
    { word: "Soft", forbidden: ["Hard", "Pillow", "Fluffy", "Touch", "Bed"] },

    // --- EXTENDED MISC ---
    { word: "Birthday", forbidden: ["Cake", "Party", "Happy", "Present", "Age"] },
    { word: "Christmas", forbidden: ["Santa", "Tree", "Present", "Holiday", "December"] },
    { word: "Halloween", forbidden: ["Ghost", "Candy", "Costume", "Pumpkin", "October"] },
    { word: "Easter", forbidden: ["Bunny", "Egg", "Basket", "Spring", "Sunday"] },
    { word: "Thanksgiving", forbidden: ["Turkey", "Eat", "Food", "November", "Family"] },
    { word: "Wedding", forbidden: ["Marriage", "Bride", "Groom", "Ring", "Dress"] },
    { word: "Summer", forbidden: ["Hot", "Sun", "Beach", "Season", "School"] },
    { word: "Winter", forbidden: ["Cold", "Snow", "Ice", "Season", "Coat"] },
    { word: "Spring", forbidden: ["Flower", "Season", "Rain", "Green", "Grow"] },
    { word: "Fall", forbidden: ["Autumn", "Leaves", "Season", "Orange", "Cool"] },
    { word: "Morning", forbidden: ["Night", "Wake", "Sun", "Breakfast", "Early"] },
    { word: "Night", forbidden: ["Day", "Sleep", "Dark", "Moon", "Bed"] },
    { word: "Dream", forbidden: ["Sleep", "Night", "Imagine", "Head", "Bed"] },
    { word: "Nightmare", forbidden: ["Bad", "Dream", "Scary", "Sleep", "Night"] },
    { word: "Ghost", forbidden: ["Boo", "Scary", "Spirit", "White", "Haunted"] },
    { word: "Vampire", forbidden: ["Blood", "Dracula", "Teeth", "Bat", "Neck"] },
    { word: "Witch", forbidden: ["Broom", "Magic", "Spell", "Hat", "Green"] },
    { word: "Zombie", forbidden: ["Dead", "Brain", "Walk", "Monster", "Undead"] },
    { word: "Monster", forbidden: ["Scary", "Bed", "Closet", "Creature", "Fright"] },
    { word: "Alien", forbidden: ["Space", "UFO", "Green", "Mars", "Planet"] },
    { word: "Robot", forbidden: ["Machine", "Metal", "Computer", "Future", "Beep"] },
    { word: "Superhero", forbidden: ["Power", "Cape", "Save", "Comic", "Villain"] },
    { word: "Princess", forbidden: ["Prince", "Crown", "Dress", "Royal", "Castle"] },
    { word: "Money", forbidden: ["Cash", "Dollar", "Buy", "Coin", "Rich"] },
    { word: "Time", forbidden: ["Clock", "Watch", "Hour", "Minute", "Second"] },
    { word: "Music", forbidden: ["Song", "Listen", "Band", "Radio", "Sound"] },
    { word: "Art", forbidden: ["Paint", "Draw", "Picture", "Museum", "Create"] },
    { word: "Science", forbidden: ["Experiment", "Lab", "Test", "Chemistry", "Study"] },
    { word: "Math", forbidden: ["Numbers", "Add", "School", "Count", "Problem"] },
    { word: "History", forbidden: ["Past", "Old", "Learn", "Dates", "Subject"] },
    { word: "Geography", forbidden: ["Map", "World", "Earth", "Place", "Country"] },
    { word: "Map", forbidden: ["World", "Place", "Direction", "Paper", "Lost"] },
    { word: "Flag", forbidden: ["Country", "Wave", "Pole", "Symbol", "Colors"] },
    { word: "Game", forbidden: ["Play", "Win", "Lose", "Fun", "Board"] },
    { word: "Toy", forbidden: ["Play", "Kid", "Doll", "Game", "Store"] },
    { word: "Party", forbidden: ["Fun", "Birthday", "Celebrate", "Friends", "Balloon"] },
    { word: "Present", forbidden: ["Gift", "Birthday", "Wrap", "Box", "Give"] },
    { word: "Balloon", forbidden: ["Air", "Pop", "Float", "Rubber", "Color"] },
    { word: "Magic", forbidden: ["Trick", "Wand", "Wizard", "Hat", "Spell"] },
    { word: "Circus", forbidden: ["Clown", "Tent", "Animals", "Show", "Acrobat"] },
    { word: "Ninja", forbidden: ["Stealth", "Black", "Fight", "Japan", "Sword"] },
    { word: "Cowboy", forbidden: ["Horse", "Hat", "West", "Boots", "Ranch"] },
    { word: "Fairy", forbidden: ["Wings", "Magic", "Small", "Fly", "Tinkerbell"] },
    { word: "Mermaid", forbidden: ["Ocean", "Tail", "Swim", "Fish", "Ariel"] },

    // --- EMOTIONS & FEELINGS ---
    { word: "Excited", forbidden: ["Happy", "Energy", "Thrilled", "Can't Wait", "Fun"] },
    { word: "Bored", forbidden: ["Tired", "Nothing", "Do", "Fun", "Sleepy"] },
    { word: "Nervous", forbidden: ["Scared", "Shake", "Worried", "Test", "Anxious"] },
    { word: "Scared", forbidden: ["Afraid", "Ghost", "Fear", "Terrified", "Spooky"] },
    { word: "Surprised", forbidden: ["Shocked", "Unexpected", "Gift", "Party", "Jump"] },
    { word: "Tired", forbidden: ["Sleep", "Bed", "Nap", "Exhausted", "Yawn"] },
    { word: "Hungry", forbidden: ["Food", "Eat", "Stomach", "Starving", "Dinner"] },
    { word: "Thirsty", forbidden: ["Drink", "Water", "Dry", "Parched", "Liquid"] },
    { word: "Lonely", forbidden: ["Alone", "Friends", "Sad", "Single", "Person"] },
    { word: "Embarrassed", forbidden: ["Red", "Face", "Shy", "Mistake", "Awkward"] },
    { word: "Proud", forbidden: ["Happy", "Accomplish", "Good", "Parent", "Win"] },
    { word: "Jealous", forbidden: ["Want", "Envy", "Green", "Have", "Other"] },
    { word: "Confused", forbidden: ["Understand", "Question", "Lost", "Think", "Puzzle"] },
    { word: "Guilty", forbidden: ["Bad", "Did", "Wrong", "Crime", "Sorry"] },
    { word: "Curious", forbidden: ["Question", "Wonder", "Know", "Ask", "Interest"] },
    { word: "Brave", forbidden: ["Scared", "Fear", "Hero", "Strong", "Courage"] },
    { word: "Shy", forbidden: ["Quiet", "Talk", "Scared", "People", "Hide"] },
    { word: "Calm", forbidden: ["Peace", "Quiet", "Relax", "Stress", "Chill"] },
    { word: "Stress", forbidden: ["Worry", "Work", "School", "Relax", "Calm"] },
    { word: "Hope", forbidden: ["Wish", "Dream", "Want", "Future", "Believe"] }
];

module.exports = { forbiddenWordsCards };
